<?php

namespace App\Livewire\Admin\TipoConsultas;

use App\Models\TipoConsulta;
use App\Models\Empresa;
use App\Models\Sucursal;
use Livewire\Component;
use Livewire\Attributes\Title;
use App\Traits\HasDynamicLayout;

#[Title('Editar Tipo de Atención')]
class Edit extends Component
{
    use HasDynamicLayout;

   public $nombre;
    public $codigo;
    public $descripcion;
    public $color = '#3B82F6';
    public $icono = 'fa-stethoscope';
    public $requiere_cita_previa = true;
    public $status = true;
    public $empresa_id;
    public $sucursal_id;
    public $tipoConsulta;

    public $empresas;
    public $sucursales = [];

    protected $rules = [
        'nombre' => 'required|string|max:255',
        'descripcion' => 'nullable|string|max:1000',
        'color' => 'required|string|max:7',
        'icono' => 'required|string|max:50',
        'status' => 'boolean',
        'empresa_id' => 'required|exists:empresas,id',
        'sucursal_id' => 'nullable|exists:sucursales,id',
    ];

    protected $messages = [
        'nombre.required' => 'El nombre es obligatorio.',
        'color.required' => 'El color es obligatorio.',
        'icono.required' => 'El icono es obligatorio.',
        'empresa_id.required' => 'La empresa es obligatoria.',
    ];

    public function mount( $tipoConsulta)
    {

      $tipoConsulta = TipoConsulta::find($tipoConsulta);

        $this->tipoConsulta = $tipoConsulta;
        $this->codigo = $tipoConsulta->codigo;
        $this->nombre = $tipoConsulta->nombre;
        $this->descripcion = $tipoConsulta->descripcion;
        $this->color = $tipoConsulta->color;
        $this->icono = $tipoConsulta->icono;
        $this->status = $tipoConsulta->status;
        $this->empresa_id = $tipoConsulta->empresa_id;
        $this->sucursal_id = $tipoConsulta->sucursal_id;
    }


    public function save()
    {
      
        $this->validate();

        try {
            $this->tipoConsulta->update([
                'nombre' => $this->nombre,
                'descripcion' => $this->descripcion,
                'color' => $this->color,
                'icono' => $this->icono,
                'status' => $this->status,
                'empresa_id' => $this->empresa_id,
                'sucursal_id' => $this->sucursal_id,
            ]);

             $this->dispatch('notify', [
                    'type' => 'success',
                    'message' => "Tipo de consulta '{$this->nombre}' modificado exitosamente.",
                    'duration' => 4000
                ]);
            return redirect()->route('admin.tipo-consultas.index');
        } catch (\Exception $e) {
            dd($e);
            $this->dispatch('notify', [
                'type' => 'error',
                'message' => 'Error al actualizar el tipo de consulta: ' . $e->getMessage(),
            ]);
        }
    }

     protected $iconos = [
        'fa-stethoscope' => 'Estetoscopio',
        'fa-user-md' => 'Médico',
        'fa-heartbeat' => 'Ritmo cardíaco',
        'fa-heart' => 'Corazón',
        'fa-eye' => 'Ojo',
        'fa-tooth' => 'Diente',
        'fa-bone' => 'Hueso',
        'fa-brain' => 'Cerebro',
        'fa-hand-holding-medical' => 'Mano médica',
        'fa-pills' => 'Píldoras',
        'fa-syringe' => 'Jeringa',
        'fa-thermometer-half' => 'Termómetro',
        'fa-band-aid' => 'Curita',
        'fa-wheelchair' => 'Silla de ruedas',
        'fa-ambulance' => 'Ambulancia',
        'fa-hospital' => 'Hospital',
        'fa-clinic-medical' => 'Clínica',
        'fa-microscope' => 'Microscopio',
        'fa-x-ray' => 'Rayos X',
        'fa-head-side-cough' => 'Tos',
        'fa-lungs' => 'Pulmones',
        'fa-dna' => 'ADN',
        'fa-baby' => 'Bebé',
        'fa-female' => 'Mujer',
        'fa-male' => 'Hombre',
        'fa-notes-medical' => 'Notas médicas',
        'fa-clipboard-list' => 'Portapapeles',
        'fa-calendar-check' => 'Calendario',
        'fa-clock' => 'Reloj',
        'fa-check-circle' => 'Check',
        'fa-exclamation-circle' => 'Advertencia',
        'fa-info-circle' => 'Información',
        'fa-plus-circle' => 'Más',
        'fa-minus-circle' => 'Menos',
        'fa-times-circle' => 'Cerrar',
        'fa-question-circle' => 'Pregunta',
        'fa-star' => 'Estrella',
        'fa-flag' => 'Bandera',
        'fa-bell' => 'Campana',
        'fa-envelope' => 'Correo',
        'fa-phone' => 'Teléfono',
        'fa-mobile-alt' => 'Móvil',
        'fa-print' => 'Imprimir',
        'fa-download' => 'Descargar',
        'fa-upload' => 'Subir',
        'fa-save' => 'Guardar',
        'fa-edit' => 'Editar',
        'fa-trash' => 'Eliminar',
        'fa-search' => 'Buscar',
        'fa-filter' => 'Filtrar',
        'fa-sort' => 'Ordenar',
        'fa-list' => 'Lista',
        'fa-th' => 'Cuadrícula',
        'fa-chart-bar' => 'Gráfica',
        'fa-chart-line' => 'Línea',
        'fa-chart-pie' => 'Pastel',
        'fa-file-medical' => 'Archivo médico',
        'fa-file-alt' => 'Archivo',
        'fa-folder' => 'Carpeta',
        'fa-folder-open' => 'Carpeta abierta',
        'fa-book' => 'Libro',
        'fa-book-medical' => 'Libro médico',
        'fa-graduation-cap' => 'Graduación',
        'fa-award' => 'Premio',
        'fa-certificate' => 'Certificado',
        'fa-shield-alt' => 'Escudo',
        'fa-lock' => 'Candado',
        'fa-unlock' => 'Desbloquear',
        'fa-key' => 'Llave',
        'fa-cog' => 'Configuración',
        'fa-tools' => 'Herramientas',
        'fa-wrench' => 'Llave inglesa',
        'fa-hammer' => 'Martillo',
        'fa-screwdriver' => 'Destornillador',
        'fa-plug' => 'Enchufe',
        'fa-power-off' => 'Apagar',
        'fa-play' => 'Play',
        'fa-pause' => 'Pausa',
        'fa-stop' => 'Detener',
        'fa-step-forward' => 'Siguiente',
        'fa-step-backward' => 'Anterior',
        'fa-fast-forward' => 'Avance rápido',
        'fa-fast-backward' => 'Retroceso rápido',
        'fa-redo' => 'Rehacer',
        'fa-undo' => 'Deshacer',
        'fa-sync' => 'Sincronizar',
        'fa-spinner' => 'Cargando',
        'fa-circle-notch' => 'Círculo',
        'fa-home' => 'Inicio',
        'fa-building' => 'Edificio',
        'fa-city' => 'Ciudad',
        'fa-map' => 'Mapa',
        'fa-map-marker' => 'Marcador',
        'fa-location-arrow' => 'Ubicación',
        'fa-compass' => 'Brújula',
        'fa-route' => 'Ruta',
        'fa-road' => 'Carretera',
        'fa-car' => 'Auto',
        'fa-truck' => 'Camión',
        'fa-bus' => 'Autobús',
        'fa-train' => 'Tren',
        'fa-plane' => 'Avión',
        'fa-ship' => 'Barco',
        'fa-rocket' => 'Cohete',
        'fa-satellite' => 'Satélite',
        'fa-globe' => 'Globo',
        'fa-globe-americas' => 'Américas',
        'fa-globe-europe' => 'Europa',
        'fa-globe-asia' => 'Asia',
        'fa-sun' => 'Sol',
        'fa-moon' => 'Luna',
        'fa-cloud' => 'Nube',
        'fa-cloud-sun' => 'Nube y sol',
        'fa-cloud-moon' => 'Nube y luna',
        'fa-cloud-rain' => 'Lluvia',
        'fa-cloud-snow' => 'Nieve',
        'fa-bolt' => 'Rayo',
        'fa-fire' => 'Fuego',
        'fa-water' => 'Agua',
        'fa-wind' => 'Viento',
        'fa-leaf' => 'Hoja',
        'fa-tree' => 'Árbol',
        'fa-flower' => 'Flor',
        'fa-seedling' => 'Planta',
        'fa-carrot' => 'Zanahoria',
        'fa-apple-alt' => 'Manzana',
        'fa-lemon' => 'Limón',
        'fa-pepper-hot' => 'Chile',
        'fa-ice-cream' => 'Helado',
        'fa-cookie' => 'Galleta',
        'fa-cookie-bite' => 'Galleta mordida',
        'fa-birthday-cake' => 'Pastel',
        'fa-pizza-slice' => 'Pizza',
        'fa-hamburger' => 'Hamburguesa',
        'fa-hotdog' => 'Hot dog',
        'fa-sandwich' => 'Sándwich',
        'fa-bread-slice' => 'Pan',
        'fa-cheese' => 'Queso',
        'fa-egg' => 'Huevo',
        'fa-fish' => 'Pescado',
        'fa-drumstick-bite' => 'Pollo',
        'fa-bacon' => 'Tocino',
        'fa-steak' => 'Bistec',
        'fa-coffee' => 'Café',
        'fa-mug-hot' => 'Taza caliente',
        'fa-glass-water' => 'Vaso de agua',
        'fa-wine-glass' => 'Copa de vino',
        'fa-beer' => 'Cerveza',
        'fa-cocktail' => 'Cóctel',
        'fa-whiskey-glass' => 'Whiskey',
        'fa-champagne-glasses' => 'Champagne',
        'fa-glass-cheers' => 'Brindis',
        'fa-utensils' => 'Utensilios',
        'fa-plate-wheat' => 'Plato de trigo',
        'fa-bowl-food' => 'Tazón de comida',
        'fa-candy-cane' => 'Palo de caramelo',
        'fa-lollipop' => 'Piruleta',
        'fa-gumdrop' => 'Goma de mascar',
        'fa-chocolate' => 'Chocolate',
        'fa-cupcake' => 'Pastelito',
        'fa-donut' => 'Donut',
        'fa-croissant' => 'Cruasán',
        'fa-bagel' => 'Bagel',
        'fa-pretzel' => 'Pretzel',
        'fa-popcorn' => 'Palomitas',
        'fa-candy' => 'Caramelo',
        'fa-gummy-bears' => 'Ositos de goma',
        'fa-jelly-beans' => 'Frijoles de jalea',
        'fa-hard-candy' => 'Dulce duro',
        'fa-sucker' => 'Chupón',
        'fa-toffee' => 'Tofee',
        'fa-fudge' => 'Dulce de leche',
        'fa-caramel' => 'Caramelo líquido',
        'fa-nougat' => 'Nuez',
        'fa-marshmallow' => 'Malvavisco',
        'fa-waffle' => 'Gofre',
        'fa-pancake' => 'Panqueque',
        'fa-french-fries' => 'Papas fritas',
        'fa-onion-rings' => 'Anillos de cebolla',
        'fa-chicken-nuggets' => 'Nuggets de pollo',
        'fa-taco' => 'Taco',
        'fa-burrito' => 'Burrito',
        'fa-quesadilla' => 'Quesadilla',
        'fa-nachos' => 'Nachos',
        'fa-guacamole' => 'Guacamole',
        'fa-salsa' => 'Salsa',
        'fa-sour-cream' => 'Crema agria',
        'fa-mustard' => 'Mostaza',
        'fa-ketchup' => 'Ketchup',
        'fa-mayo' => 'Mayonesa',
        'fa-ranch' => 'Aderezo ranch',
        'fa-vinegar' => 'Vinagre',
        'fa-oil' => 'Aceite',
        'fa-salt' => 'Sal',
        'fa-pepper' => 'Pimienta',
        'fa-sugar' => 'Azúcar',
        'fa-honey' => 'Miel',
        'fa-syrup' => 'Jarabe',
        'fa-jam' => 'Mermelada',
        'fa-jelly' => 'Jalea',
        'fa-peanut-butter' => 'Mantequilla de maní',
        'fa-nutella' => 'Nutella',
        'fa-marshmallow-fluff' => 'Malvavisco fluff',
        'fa-whipped-cream' => 'Crema batida',
        'fa-cool-whip' => 'Crema cool whip',
        'fa-ice-cream-cone' => 'Cono de helado',
        'fa-sundae' => 'Sundae',
        'fa-milkshake' => 'Malteada',
        'fa-smoothie' => 'Batido',
        'fa-frappe' => 'Frappe',
        'fa-latte' => 'Latte',
        'fa-cappuccino' => 'Cappuccino',
        'fa-espresso' => 'Espresso',
        'fa-macchiato' => 'Macchiato',
        'fa-mocha' => 'Mocha',
        'fa-americano' => 'Americano',
        'fa-iced-coffee' => 'Café helado',
        'fa-cold-brew' => 'Cold brew',
        'fa-frappuccino' => 'Frappuccino',
        'fa-bubble-tea' => 'Té de burbujas',
        'fa-green-tea' => 'Té verde',
        'fa-black-tea' => 'Té negro',
        'fa-herbal-tea' => 'Té de hierbas',
        'fa-chai-tea' => 'Té chai',
        'fa-matcha' => 'Matcha',
        'fa-lemonade' => 'Limonada',
        'fa-orange-juice' => 'Jugo de naranja',
        'fa-apple-juice' => 'Jugo de manzana',
        'fa-cranberry-juice' => 'Jugo de arándano',
        'fa-grape-juice' => 'Jugo de uva',
        'fa-tomato-juice' => 'Jugo de tomate',
        'fa-vegetable-juice' => 'Jugo de vegetales',
        'fa-smoothie-bowl' => 'Tazón de batido',
        'fa-acai-bowl' => 'Tazón de acai',
        'fa-pitaya-bowl' => 'Tazón de pitaya',
        'fa-greek-yogurt' => 'Yogur griego',
        'fa-frozen-yogurt' => 'Yogur congelado',
        'fa-kefir' => 'Kéfir',
        'fa-buttermilk' => 'Suero de leche',
        'fa-condensed-milk' => 'Leche condensada',
        'fa-evaporated-milk' => 'Leche evaporada',
        'fa-powdered-milk' => 'Leche en polvo',
        'fa-cream-cheese' => 'Queso crema',
        'fa-cottage-cheese' => 'Queso cottage',
        'fa-ricotta' => 'Ricotta',
        'fa-mozzarella' => 'Mozzarella',
        'fa-parmesan' => 'Parmesano',
        'fa-cheddar' => 'Cheddar',
        'fa-swiss' => 'Suizo',
        'fa-provolone' => 'Provolone',
        'fa-gouda' => 'Gouda',
        'fa-brie' => 'Brie',
        'fa-camembert' => 'Camembert',
        'fa-blue-cheese' => 'Queso azul',
        'fa-feta' => 'Feta',
        'fa-goat-cheese' => 'Queso de cabra',
        'fa-sheep-cheese' => 'Queso de oveja',
        'fa-vegan-cheese' => 'Queso vegano',
        'fa-lactose-free' => 'Sin lactosa',
        'fa-gluten-free' => 'Sin gluten',
        'fa-sugar-free' => 'Sin azúcar',
        'fa-fat-free' => 'Sin grasa',
        'fa-low-sodium' => 'Bajo en sodio',
        'fa-organic' => 'Orgánico',
        'fa-natural' => 'Natural',
        'fa-fresh' => 'Fresco',
        'fa-dried' => 'Seco',
        'fa-canned' => 'Enlatado',
        'fa-frozen' => 'Congelado',
        'fa-smoked' => 'Ahumado',
        'fa-cured' => 'Curado',
        'fa-fermented' => 'Fermentado',
        'fa-pickled' => 'En escabeche',
        'fa-marinated' => 'Marinado',
        'fa-seasoned' => 'Condimentado',
        'fa-spiced' => 'Especiado',
        'fa-herbed' => 'Con hierbas',
        'fa-flavored' => 'Saborizado',
        'fa-infused' => 'Infundido',
        'fa-extracted' => 'Extraído',
        'fa-concentrated' => 'Concentrado',
        'fa-diluted' => 'Diluido',
        'fa-mixed' => 'Mezclado',
        'fa-blended' => 'Mezcla',
        'fa-pureed' => 'Pure',
        'fa-mashed' => 'Machacado',
        'fa-crushed' => 'Triturado',
        'fa-ground' => 'Molido',
        'fa-chopped' => 'Picado',
        'fa-diced' => 'En cubos',
        'fa-sliced' => 'En rodajas',
        'fa-shredded' => 'Rallado',
        'fa-grated' => 'Rayado',
        'fa-peeled' => 'Pelado',
        'fa-cored' => 'Sin corazón',
        'fa-seeded' => 'Sin semillas',
        'fa-stemmed' => 'Sin tallo',
        'fa-minced' => 'Picado fino',
        'fa-crumbled' => 'Desmenuzado',
        'fa-cubed' => 'En cubos',
        'fa-julienned' => 'En juliana',
        'fa-batonnet' => 'En bastones',
        'fa-brunoise' => 'Brunoise',
        'fa-chiffonade' => 'Chiffonade',
        'fa-zested' => 'Ralladura',
        'fa-scored' => 'Marcado',
        'fa-pierced' => 'Perforado',
        'fa-tenderized' => 'Ablandado',
        'fa-butterflied' => 'Mariposa',
        'fa-boned' => 'Deshuesado',
        'fa-skinned' => 'Sin piel',
        'fa-trimmed' => 'Recortado',
        'fa-cleaned' => 'Limpiado',
        'fa-washed' => 'Lavado',
        'fa-rinsed' => 'Enjuagado',
        'fa-soaked' => 'Remojado',
        'fa-drained' => 'Escurrido',
        'fa-strained' => 'Colado',
        'fa-filtered' => 'Filtrado',
        'fa-clarified' => 'Clarificado',
        'fa-decanted' => 'Decantado',
        'fa-skimmed' => 'Desnatado',
        'fa-degreased' => 'Desgrasado',
        'fa-defatted' => 'Sin grasa',
        'fa-dehydrated' => 'Deshidratado',
        'fa-desiccated' => 'Desecado',
        'fa-lyophilized' => 'Liofilizado',
        'fa-spray-dried' => 'Secado por aspersión',
        'fa-freeze-dried' => 'Secado por congelación',
        'fa-vacuum-dried' => 'Secado al vacío',
        'fa-oven-dried' => 'Secado en horno',
        'fa-sun-dried' => 'Secado al sol',
        'fa-air-dried' => 'Secado al aire',
        'fa-cold-smoked' => 'Ahumado en frío',
        'fa-hot-smoked' => 'Ahumado en caliente',
        'fa-liquid-smoked' => 'Ahumado líquido',
        'fa-salt-cured' => 'Curado con sal',
        'fa-sugar-cured' => 'Curado con azúcar',
        'fa-brine-cured' => 'Curado en salmuera',
        'fa-dry-cured' => 'Curado seco',
        'fa-wet-cured' => 'Curado húmedo',
        'fa-combination-cured' => 'Curado combinado',
        'fa-injection-cured' => 'Curado por inyección',
        'fa-tumbling-cured' => 'Curado por tumbling',
        'fa-massaged' => 'Masaje',
        'fa-pressed' => 'Presionado',
        'fa-molded' => 'Moldeado',
        'fa-shaped' => 'Formado',
        'fa-formed' => 'Formado',
        'fa-extruded' => 'Extruido',
        'fa-spun' => 'Hilado',
        'fa-stretched' => 'Estirado',
        'fa-rolled' => 'Enrollado',
        'fa-folded' => 'Doblado',
        'fa-layered' => 'En capas',
        'fa-stacked' => 'Apilado',
        'fa-arranged' => 'Arreglado',
        'fa-plated' => 'Emplatado',
        'fa-garnished' => 'Guarnecido',
        'fa-decorated' => 'Decorado',
        'fa-topped' => 'Con topping',
        'fa-filled' => 'Relleno',
        'fa-stuffed' => 'Relleno',
        'fa-injected' => 'Inyectado',
        'fa-infused' => 'Infundido',
        'fa-marinated-injected' => 'Marinado e inyectado',
        'fa-basted' => 'Pincelado',
        'fa-glazed' => 'Glaseado',
        'fa-coated' => 'Recubierto',
        'fa-breaded' => 'Empanizado',
        'fa-battered' => 'Rebozado',
        'fa-floured' => 'Enharinado',
        'fa-seasoned-coated' => 'Recubierto condimentado',
        'fa-spice-rubbed' => 'Frotado con especias',
        'fa-herb-crusted' => 'Corteza de hierbas',
        'fa-nut-crusted' => 'Corteza de nueces',
        'fa-seed-crusted' => 'Corteza de semillas',
        'fa-cereal-crusted' => 'Corteza de cereal',
        'fa-breadcrumb-crusted' => 'Corteza de pan rallado',
        'fa-cheese-crusted' => 'Corteza de queso',
        'fa-vegetable-crusted' => 'Corteza de vegetales',
        'fa-fruit-crusted' => 'Corteza de frutas',
        'fa-mushroom-crusted' => 'Corteza de hongos',
        'fa-seafood-crusted' => 'Corteza de mariscos',
        'fa-meat-crusted' => 'Corteza de carne',
        'fa-poultry-crusted' => 'Corteza de ave',
        'fa-game-crusted' => 'Corteza de caza',
        'fa-offal-crusted' => 'Corteza de vísceras',
        'fa-fat-crusted' => 'Corteza de grasa',
        'fa-skin-crusted' => 'Corteza de piel',
        'fa-bone-crusted' => 'Corteza de hueso',
        'fa-cartilage-crusted' => 'Corteza de cartílago',
        'fa-connective-tissue-crusted' => 'Corteza de tejido conectivo',
        'fa-muscle-crusted' => 'Corteza de músculo',
        'fa-blood-crusted' => 'Corteza de sangre',
        'fa-plasma-crusted' => 'Corteza de plasma',
        'fa-serum-crusted' => 'Corteza de suero',
        'fa-enzyme-crusted' => 'Corteza de enzima',
        'fa-hormone-crusted' => 'Corteza de hormona',
        'fa-vitamin-crusted' => 'Corteza de vitamina',
        'fa-mineral-crusted' => 'Corteza de mineral',
        'fa-protein-crusted' => 'Corteza de proteína',
        'fa-carbohydrate-crusted' => 'Corteza de carbohidrato',
        'fa-lipid-crusted' => 'Corteza de lípido',
        'fa-fiber-crusted' => 'Corteza de fibra',
        'fa-water-crusted' => 'Corteza de agua',
        'fa-air-crusted' => 'Corteza de aire',
        'fa-fire-crusted' => 'Corteza de fuego',
        'fa-earth-crusted' => 'Corteza de tierra',
        'fa-metal-crusted' => 'Corteza de metal',
        'fa-plastic-crusted' => 'Corteza de plástico',
        'fa-glass-crusted' => 'Corteza de vidrio',
        'fa-ceramic-crusted' => 'Corteza de cerámica',
        'fa-paper-crusted' => 'Corteza de papel',
        'fa-wood-crusted' => 'Corteza de madera',
        'fa-stone-crusted' => 'Corteza de piedra',
        'fa-concrete-crusted' => 'Corteza de concreto',
        'fa-asphalt-crusted' => 'Corteza de asfalto',
        'fa-rubber-crusted' => 'Corteza de caucho',
        'fa-leather-crusted' => 'Corteza de cuero',
        'fa-fabric-crusted' => 'Corteza de tela',
        'fa-textile-crusted' => 'Corteza de textil',
        'fa-synthetic-crusted' => 'Corteza sintética',
        'fa-natural-crusted' => 'Corteza natural',
        'fa-organic-crusted' => 'Corteza orgánica',
        'fa-inorganic-crusted' => 'Corteza inorgánica',
        'fa-biological-crusted' => 'Corteza biológica',
        'fa-chemical-crusted' => 'Corteza química',
        'fa-physical-crusted' => 'Corteza física',
        'fa-mechanical-crusted' => 'Corteza mecánica',
        'fa-thermal-crusted' => 'Corteza térmica',
        'fa-electrical-crusted' => 'Corteza eléctrica',
        'fa-magnetic-crusted' => 'Corteza magnética',
        'fa-optical-crusted' => 'Corteza óptica',
        'fa-acoustic-crusted' => 'Corteza acústica',
        'fa-radioactive-crusted' => 'Corteza radiactiva',
        'fa-nuclear-crusted' => 'Corteza nuclear',
        'fa-atomic-crusted' => 'Corteza atómica',
        'fa-molecular-crusted' => 'Corteza molecular',
        'fa-ionic-crusted' => 'Corteza iónica',
        'fa-covalent-crusted' => 'Corteza covalente',
        'fa-metallic-crusted' => 'Corteza metálica',
        'fa-ionic-bonded' => 'Enlace iónico',
        'fa-covalent-bonded' => 'Enlace covalente',
        'fa-metallic-bonded' => 'Enlace metálico',
        'fa-hydrogen-bonded' => 'Enlace de hidrógeno',
        'fa-van-der-waals-bonded' => 'Enlace de Van der Waals',
        'fa-dipole-dipole-bonded' => 'Enlace dipolo-dipolo',
        'fa-induced-dipole-bonded' => 'Enlace dipolo inducido',
        'fa-london-dispersion-bonded' => 'Dispersión de London',
        'fa-keesom-interaction' => 'Interacción de Keesom',
        'fa-debye-interaction' => 'Interacción de Debye',
        'fa-london-interaction' => 'Interacción de London',
        'fa-casimir-effect' => 'Efecto Casimir',
        'fa-van-der-waals-force' => 'Fuerza de Van der Waals',
        'fa-electrostatic-force' => 'Fuerza electrostática',
        'fa-magnetic-force' => 'Fuerza magnética',
        'fa-gravitational-force' => 'Fuerza gravitacional',
        'fa-nuclear-force' => 'Fuerza nuclear',
        'fa-weak-force' => 'Fuerza débil',
        'fa-strong-force' => 'Fuerza fuerte',
        'fa-fundamental-force' => 'Fuerza fundamental',
        'fa-residual-force' => 'Fuerza residual',
        'fa-exchange-force' => 'Fuerza de intercambio',
        'fa-pauli-exclusion' => 'Exclusión de Pauli',
        'fa-heisenberg-uncertainty' => 'Incertidumbre de Heisenberg',
        'fa-schrödinger-equation' => 'Ecuación de Schrödinger',
        'fa-dirac-equation' => 'Ecuación de Dirac',
        'fa-klein-gordon-equation' => 'Ecuación de Klein-Gordon',
        'fa-proca-equation' => 'Ecuación de Proca',
        'fa-maxwell-equations' => 'Ecuaciones de Maxwell',
        'fa-lorentz-force' => 'Fuerza de Lorentz',
        'fa-faraday-law' => 'Ley de Faraday',
        'fa-ampere-law' => 'Ley de Ampère',
        'fa-gauss-law' => 'Ley de Gauss',
        'fa-biot-savart-law' => 'Ley de Biot-Savart',
        'fa-coulomb-law' => 'Ley de Coulomb',
        'fa-newton-law' => 'Ley de Newton',
        'fa-kepler-law' => 'Ley de Kepler',
        'fa-thermodynamics' => 'Termodinámica',
        'fa-statistical-mechanics' => 'Mecánica estadística',
        'fa-quantum-mechanics' => 'Mecánica cuántica',
        'fa-relativity' => 'Relatividad',
        'fa-special-relativity' => 'Relatividad especial',
        'fa-general-relativity' => 'Relatividad general',
        'fa-unified-field-theory' => 'Teoría unificada de campos',
        'fa-string-theory' => 'Teoría de cuerdas',
        'fa-m-theory' => 'Teoría M',
        'fa-loop-quantum-gravity' => 'Gravedad cuántica de lazos',
        'fa-twistor-theory' => 'Teoría de torsores',
        'fa-supersymmetry' => 'Supersimetría',
        'fa-supergravity' => 'Supergravedad',
        'fa-grand-unification' => 'Gran unificación',
        'fa-theory-of-everything' => 'Teoría del todo'
    ];


    public function getEmpresasProperty()
    {
       $this->empresas = Empresa::all();
        
        if (!auth()->user()->hasRole('Super Administrador')) {
            $this->empresa_id = auth()->user()->empresa_id;
            $this->sucursal_id = auth()->user()->sucursal_id;
        }
    }

    
    public function updatedEmpresaId($value)
    {
        $this->sucursales = Sucursal::where('empresa_id', $value)->get();
        $this->sucursal_id = null;
    }

    public function getSucursalesProperty()
    {
        return Sucursal::when($this->empresa_id, function ($query) {
                $query->where('empresa_id', $this->empresa_id);
            })
            ->forUser()
            ->get();
    }

    public function render()
    {
        return view('livewire.admin.tipo-consultas.edit', [
            'empresas' => $this->empresas,
            'sucursales' => $this->sucursales,
            'iconos' => $this->iconos
        ])->layout($this->getLayout());
    }
}